from pathlib import Path

from bridging.MD.paths import DATA_CSV, GENERATED_DIR
from bridging.featurization.config import FEATURES_BASENAME

DEFAULT_DATASET = DATA_CSV
DEFAULT_CVAE_CHECKPOINT = Path("models") / "cvae.pt"
DEFAULT_PRODIGY_DIR = GENERATED_DIR / "PRODIGY"
DEFAULT_MMGBSA_DIR = GENERATED_DIR / "MMGBSA"
DEFAULT_OUT_DIR = GENERATED_DIR / "regression"
DEFAULT_FEATURE_FILENAME = FEATURES_BASENAME
