#!/bin/bash -l

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

if [ -f ".venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
fi

PYTHON="${PYTHON:-$REPO_ROOT/.venv/bin/python}"
if [ ! -x "$PYTHON" ]; then
  PYTHON="$(command -v python3 || command -v python)"
fi
export PYTHONPATH="${PYTHONPATH:-src}"

DATASET="${DATASET:-src/bridging/processedData/PPB_Affinity_broad_pairuniq_train80_test20.csv}"
DATASET_STEM="$(basename "$DATASET" .csv)"
SCRATCH_ROOT="${SCRATCH_ROOT:-$HOME/scratch}"
MD_ROOT="${MD_ROOT:-$SCRATCH_ROOT/MD_datasets/$DATASET_STEM}"
PDB_CACHE_ROOT="${PDB_CACHE_ROOT:-$SCRATCH_ROOT/pdb_cache}"
RECORDS="${RECORDS:-src/bridging/generatedData/graphvae/${DATASET_STEM}_parallel_prepare_fullfeatures_v1/prepared/graph_records.pt}"

GPU_CPUS_PER_TASK="${GPU_CPUS_PER_TASK:-8}"
VIEW_GRAPH_VIEWS="${VIEW_GRAPH_VIEWS:-full,interface}"
VIEW_INTERFACE_POLICIES="${VIEW_INTERFACE_POLICIES:-md_closest_pair_patch}"
VIEW_MATCH_INTERFACE_SUBSET="${VIEW_MATCH_INTERFACE_SUBSET:-true}"
VIEW_OUT_DIR="${VIEW_OUT_DIR:-src/bridging/generatedData/graphvae/${DATASET_STEM}_views_force_mdiface_v1}"

DEVICE="${DEVICE:-cuda}"
MAX_EPOCHS="${MAX_EPOCHS:-120}"
PATIENCE="${PATIENCE:-20}"
BATCH_SIZE="${BATCH_SIZE:-16}"
NUM_WORKERS="${NUM_WORKERS:-4}"
RIDGE_CV_FOLDS="${RIDGE_CV_FOLDS:-5}"
RIDGE_CV_REPEATS="${RIDGE_CV_REPEATS:-3}"
RIDGE_CV_INNER_FOLDS="${RIDGE_CV_INNER_FOLDS:-5}"
AFFINITY_WEIGHT="${AFFINITY_WEIGHT:-1.0}"
MODES="${MODES:-S,SD}"
LATENT_DIMS="${LATENT_DIMS:-8,16,32,64}"
SUPERVISION_MODES="${SUPERVISION_MODES:-unsupervised,semi_supervised}"

FULL_P1_TARGET_POLICIES="${FULL_P1_TARGET_POLICIES:-shared_static,shared_all,all_inputs,all_nonidentity,mode_specific}"
FULL_P1_INCLUDE_SUPERVISED_BASELINE="${FULL_P1_INCLUDE_SUPERVISED_BASELINE:-false}"
FULL_P1_OUT_DIR="${FULL_P1_OUT_DIR:-src/bridging/generatedData/graphvae/${DATASET_STEM}_sweep_force_fullonly_part1_v1}"

FULL_P2_TARGET_POLICIES="${FULL_P2_TARGET_POLICIES:-sd_dynamic_all,sd_static_plus_dynamic_all,sd_static_plus_dynamic_nodes,sd_static_plus_dynamic_edges}"
FULL_P2_INCLUDE_SUPERVISED_BASELINE="${FULL_P2_INCLUDE_SUPERVISED_BASELINE:-true}"
FULL_P2_OUT_DIR="${FULL_P2_OUT_DIR:-src/bridging/generatedData/graphvae/${DATASET_STEM}_sweep_force_fullonly_part2_v1}"

INTERFACE_P1_TARGET_POLICIES="${INTERFACE_P1_TARGET_POLICIES:-shared_static,shared_all,all_inputs,all_nonidentity,mode_specific}"
INTERFACE_P1_INCLUDE_SUPERVISED_BASELINE="${INTERFACE_P1_INCLUDE_SUPERVISED_BASELINE:-false}"
INTERFACE_P1_OUT_DIR="${INTERFACE_P1_OUT_DIR:-src/bridging/generatedData/graphvae/${DATASET_STEM}_sweep_force_interface_part1_v1}"

INTERFACE_P2_TARGET_POLICIES="${INTERFACE_P2_TARGET_POLICIES:-sd_dynamic_all,sd_static_plus_dynamic_all,sd_static_plus_dynamic_nodes,sd_static_plus_dynamic_edges}"
INTERFACE_P2_INCLUDE_SUPERVISED_BASELINE="${INTERFACE_P2_INCLUDE_SUPERVISED_BASELINE:-true}"
INTERFACE_P2_OUT_DIR="${INTERFACE_P2_OUT_DIR:-src/bridging/generatedData/graphvae/${DATASET_STEM}_sweep_force_interface_part2_v1}"

BASELINE_HIDDEN_DIMS="${BASELINE_HIDDEN_DIMS:-128,256}"
BASELINE_NUM_LAYERS_LIST="${BASELINE_NUM_LAYERS_LIST:-3,4}"
BASELINE_LR="${BASELINE_LR:-3e-4}"
BASELINE_WEIGHT_DECAY="${BASELINE_WEIGHT_DECAY:-1e-5}"

mkdir -p logs

echo "[INFO] dataset=$DATASET"
echo "[INFO] records=$RECORDS"
echo "[INFO] md_root=$MD_ROOT"
echo "[INFO] pdb_cache_root=$PDB_CACHE_ROOT"
echo "[INFO] gpu_cpus_per_task=$GPU_CPUS_PER_TASK"

VIEW_JID=$(
  env \
    DATASET="$DATASET" \
    RECORDS="$RECORDS" \
    MD_ROOT="$MD_ROOT" \
    PDB_CACHE_ROOT="$PDB_CACHE_ROOT" \
    GRAPH_VIEWS="$VIEW_GRAPH_VIEWS" \
    INTERFACE_POLICIES="$VIEW_INTERFACE_POLICIES" \
    MATCH_INTERFACE_SUBSET="$VIEW_MATCH_INTERFACE_SUBSET" \
    OUT_DIR="$VIEW_OUT_DIR" \
    sbatch \
    --export=ALL \
    hpc/graphvae_materialize_views_cpu.sbatch \
    | awk '{print $4}'
)
echo "[SUBMIT] VIEW_JID=$VIEW_JID"

FULL_P1_JID=$(
  env \
    DATASET="$DATASET" \
    RECORDS="$RECORDS" \
    DEVICE="$DEVICE" \
    MAX_EPOCHS="$MAX_EPOCHS" \
    PATIENCE="$PATIENCE" \
    BATCH_SIZE="$BATCH_SIZE" \
    NUM_WORKERS="$NUM_WORKERS" \
    RIDGE_CV_FOLDS="$RIDGE_CV_FOLDS" \
    RIDGE_CV_REPEATS="$RIDGE_CV_REPEATS" \
    RIDGE_CV_INNER_FOLDS="$RIDGE_CV_INNER_FOLDS" \
    AFFINITY_WEIGHT="$AFFINITY_WEIGHT" \
    MODES="$MODES" \
    LATENT_DIMS="$LATENT_DIMS" \
    SUPERVISION_MODES="$SUPERVISION_MODES" \
    GRAPH_VIEWS="full" \
    TARGET_POLICIES="$FULL_P1_TARGET_POLICIES" \
    INCLUDE_SUPERVISED_BASELINE="$FULL_P1_INCLUDE_SUPERVISED_BASELINE" \
    OUT_DIR="$FULL_P1_OUT_DIR" \
    sbatch \
    --cpus-per-task="$GPU_CPUS_PER_TASK" \
    --export=ALL \
    hpc/graphvae_saved_sweep_gpu.sbatch \
    | awk '{print $4}'
)
echo "[SUBMIT] FULL_P1_JID=$FULL_P1_JID"

FULL_P2_JID=$(
  env \
    DATASET="$DATASET" \
    RECORDS="$RECORDS" \
    DEVICE="$DEVICE" \
    MAX_EPOCHS="$MAX_EPOCHS" \
    PATIENCE="$PATIENCE" \
    BATCH_SIZE="$BATCH_SIZE" \
    NUM_WORKERS="$NUM_WORKERS" \
    RIDGE_CV_FOLDS="$RIDGE_CV_FOLDS" \
    RIDGE_CV_REPEATS="$RIDGE_CV_REPEATS" \
    RIDGE_CV_INNER_FOLDS="$RIDGE_CV_INNER_FOLDS" \
    AFFINITY_WEIGHT="$AFFINITY_WEIGHT" \
    MODES="$MODES" \
    LATENT_DIMS="$LATENT_DIMS" \
    SUPERVISION_MODES="$SUPERVISION_MODES" \
    GRAPH_VIEWS="full" \
    TARGET_POLICIES="$FULL_P2_TARGET_POLICIES" \
    INCLUDE_SUPERVISED_BASELINE="$FULL_P2_INCLUDE_SUPERVISED_BASELINE" \
    BASELINE_HIDDEN_DIMS="$BASELINE_HIDDEN_DIMS" \
    BASELINE_NUM_LAYERS_LIST="$BASELINE_NUM_LAYERS_LIST" \
    BASELINE_LR="$BASELINE_LR" \
    BASELINE_WEIGHT_DECAY="$BASELINE_WEIGHT_DECAY" \
    OUT_DIR="$FULL_P2_OUT_DIR" \
    sbatch \
    --cpus-per-task="$GPU_CPUS_PER_TASK" \
    --export=ALL \
    hpc/graphvae_saved_sweep_gpu.sbatch \
    | awk '{print $4}'
)
echo "[SUBMIT] FULL_P2_JID=$FULL_P2_JID"

INTERFACE_DEP="afterok:${VIEW_JID},afterok:${FULL_P1_JID},afterok:${FULL_P2_JID}"

INT_P1_JID=$(
  env \
    DATASET="$DATASET" \
    RECORDS="$RECORDS" \
    MD_ROOT="$MD_ROOT" \
    PDB_CACHE_ROOT="$PDB_CACHE_ROOT" \
    PREBUILT_VIEW_ROOT="$VIEW_OUT_DIR" \
    DEVICE="$DEVICE" \
    MAX_EPOCHS="$MAX_EPOCHS" \
    PATIENCE="$PATIENCE" \
    BATCH_SIZE="$BATCH_SIZE" \
    NUM_WORKERS="$NUM_WORKERS" \
    RIDGE_CV_FOLDS="$RIDGE_CV_FOLDS" \
    RIDGE_CV_REPEATS="$RIDGE_CV_REPEATS" \
    RIDGE_CV_INNER_FOLDS="$RIDGE_CV_INNER_FOLDS" \
    AFFINITY_WEIGHT="$AFFINITY_WEIGHT" \
    MODES="$MODES" \
    LATENT_DIMS="$LATENT_DIMS" \
    SUPERVISION_MODES="$SUPERVISION_MODES" \
    GRAPH_VIEWS="interface" \
    INTERFACE_POLICIES="$VIEW_INTERFACE_POLICIES" \
    MATCH_INTERFACE_SUBSET="$VIEW_MATCH_INTERFACE_SUBSET" \
    TARGET_POLICIES="$INTERFACE_P1_TARGET_POLICIES" \
    INCLUDE_SUPERVISED_BASELINE="$INTERFACE_P1_INCLUDE_SUPERVISED_BASELINE" \
    OUT_DIR="$INTERFACE_P1_OUT_DIR" \
    sbatch \
    --cpus-per-task="$GPU_CPUS_PER_TASK" \
    --dependency="$INTERFACE_DEP" \
    --export=ALL \
    hpc/graphvae_saved_sweep_gpu.sbatch \
    | awk '{print $4}'
)
echo "[SUBMIT] INT_P1_JID=$INT_P1_JID"

INT_P2_JID=$(
  env \
    DATASET="$DATASET" \
    RECORDS="$RECORDS" \
    MD_ROOT="$MD_ROOT" \
    PDB_CACHE_ROOT="$PDB_CACHE_ROOT" \
    PREBUILT_VIEW_ROOT="$VIEW_OUT_DIR" \
    DEVICE="$DEVICE" \
    MAX_EPOCHS="$MAX_EPOCHS" \
    PATIENCE="$PATIENCE" \
    BATCH_SIZE="$BATCH_SIZE" \
    NUM_WORKERS="$NUM_WORKERS" \
    RIDGE_CV_FOLDS="$RIDGE_CV_FOLDS" \
    RIDGE_CV_REPEATS="$RIDGE_CV_REPEATS" \
    RIDGE_CV_INNER_FOLDS="$RIDGE_CV_INNER_FOLDS" \
    AFFINITY_WEIGHT="$AFFINITY_WEIGHT" \
    MODES="$MODES" \
    LATENT_DIMS="$LATENT_DIMS" \
    SUPERVISION_MODES="$SUPERVISION_MODES" \
    GRAPH_VIEWS="interface" \
    INTERFACE_POLICIES="$VIEW_INTERFACE_POLICIES" \
    MATCH_INTERFACE_SUBSET="$VIEW_MATCH_INTERFACE_SUBSET" \
    TARGET_POLICIES="$INTERFACE_P2_TARGET_POLICIES" \
    INCLUDE_SUPERVISED_BASELINE="$INTERFACE_P2_INCLUDE_SUPERVISED_BASELINE" \
    BASELINE_HIDDEN_DIMS="$BASELINE_HIDDEN_DIMS" \
    BASELINE_NUM_LAYERS_LIST="$BASELINE_NUM_LAYERS_LIST" \
    BASELINE_LR="$BASELINE_LR" \
    BASELINE_WEIGHT_DECAY="$BASELINE_WEIGHT_DECAY" \
    OUT_DIR="$INTERFACE_P2_OUT_DIR" \
    sbatch \
    --cpus-per-task="$GPU_CPUS_PER_TASK" \
    --dependency="$INTERFACE_DEP" \
    --export=ALL \
    hpc/graphvae_saved_sweep_gpu.sbatch \
    | awk '{print $4}'
)
echo "[SUBMIT] INT_P2_JID=$INT_P2_JID"

echo
echo "Monitor:"
echo "  squeue -j ${VIEW_JID},${FULL_P1_JID},${FULL_P2_JID},${INT_P1_JID},${INT_P2_JID} -o '%.18i %.2t %.10M %.10l %.20R %.30j'"
echo "  tail -f logs/graphvae_views_${VIEW_JID}.out"
